#!/bin/bash
#$1 is bitcode file $2 is support $3 if confidence
#check to see if there are three or one arguments
if [ $# -ge 1 ]
then
	bitcode=$1
	echo "set bit code"
	#compile bitcode to graph file
	
	if [ $# -eq 3 ] 
	then
		support=$2
    	conf=$3
		#java Main bitcode support conf
		java -cp out Main "$bitcode" "$support" "$conf"
		exit 1
	fi
	
	if [ $# -eq 1 ]
	then
		#java Main bitcode
		java -cp out Main "$bitcode"
		exit 1
	else
		echo "Incorrect Parameters"
	fi
fi
